spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      location: /tmp/upload

mybatis-plus:
  mapper-locations:
    - classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.onlineshop: debug

file:
  upload-dir: /home/Tomatos/Pictures/upload/image/