spring:
  application:
    name: online-im
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/online_shop
    username: Tomatos
    password: 20030503
server:
  port: 7010

jwt:
  secret: mySecretKeyForJwtToken123456789012345678901234567890  # 请替换为更安全的密钥
  expire: 86400000  # 24小时（毫秒）