server:
  port: 7001

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/online_shop
    username: Tomatos
    password: 20030503
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: 'zjlljz'
  cache:
    type: redis
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

auth:
  white-list:
    - '/web/common/**'
    - '/web/banner/**'
    - '/web/category/**'
    - '/web/user/login'
    - '/web/user/register'
    - '/web/goods/**'

rocketmq:
  name-server: localhost:9876
  producer:
    group: online-mall-group
    send-message-timeout: 3000
  consumer:
    group: order_timeout_cancel_group

mq:
  orders:
    timeout-seconds: 1800
    cancel-topic: "order.cancel.topic"

jwt:
  secret: mySecretKeyForJwtToken123456789012345678901234567890  # 请替换为更安全的密钥
  expire: 86400000  # 24小时（毫秒）
