server:
  port: 7000
  servlet:
    context-path: /manage
  
spring:
  datasource:
    driver-class-name: ${app.datasource.driver-class-name}
    url: ${app.datasource.url}
    username: ${app.datasource.username}
    password: ${app.datasource.password}
  data:
    redis:
      host: ${app.redis.host}
      port: 6379
      password: ${app.redis.password}
      database: ${app.redis.database}
  elasticsearch:
    uris: ${app.elasticsearch.uris}
    username: ${app.elasticsearch.username}
    password: ${app.elasticsearch.password}
    connection-timeout: 5s
    socket-timeout: 15s
  cache:
    type: redis
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

rocketmq:
  producer:
    group: online-mall-group
    send-message-timeout: 3000
    namespace:
  consumer:
    group: order_timeout_cancel_group
  name-server: ${app.rocketmq.name-server}

auth:
  white-list:
    - '/auth/**'
    - '/files/**'

jwt:
  secret: ${app.jwt.secret}
  expire: 86400000  # 24小时（毫秒）

file:
  storage-type: minio
  upload:
    max-size: 5242880
    allowed-extensions:
      - jpg
      - jpeg
      - png
    allowed-mime-types:
      - image/jpeg
      - image/png
  minio:
    url: ${app.minio.url}
    access-key: ${app.minio.access-key}
    secret-key: ${app.minio.secret-key}
    bucket-name: ${app.minio.bucket-name}